name: CI

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    # Étape 1 : Checkout du code source
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies with Composer
      uses: php-actions/composer@v6
      with: 
        dependancies_install: bin/composer
        args: install

    # Étape 3 : Exécuter les tests avec PHPUnit
    - name: Run PHPUnit tests
      uses: php-actions/phpunit@v3
      with:
        vendored_phpunit_path: ./vendor/bin/phpunit  
        args: tst  
