name: CI

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies with Composer
      uses: php-actions/composer@v6
      with:
        command: install
        php_version: '8.2'
        dev: yes

    - name: Run PHPUnit tests with php-actions/phpunit
      uses: php-actions/phpunit@v3
      with:
        version: 9.6.2
        php_version: "8.2"
        php_extensions: "pdo gd xdebug"
      env:
        XDEBUG_MODE: coverage

    - name: Run PHPUnit with Cobertura coverage
      run: vendor/bin/phpunit --coverage-clover coverage.cobertura.xml || true

    - name: Generate Code Coverage Summary
      uses: irongut/CodeCoverageSummary@v1.3.0
      with:
        filename: coverage.cobertura.xml
        badge: true
        fail_below_min: true
        format: markdown
        hide_branch_rate: false
        hide_complexity: true
        indicators: true
        output: both
        thresholds: '60 80'

    - name: Add Code Coverage to GitHub Summary
      run: |
        cat coverage-results.md >> $GITHUB_STEP_SUMMARY
      if: success()
