
name: CI

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    # Étape 1 : Checkout du code source
    - name: Checkout repository
      uses: actions/checkout@v3

    # Étape 3 : Installer les dépendances avec Composer
    - name: Install dependencies with Composer
      uses: php-actions/composer@v6 
      with:
        command: install  # Utiliser "command" pour dire à Composer ce que faire
        php_version: '8.1'  # Choisir la version PHP appropriée si nécessaire
        dev: yes  # Inclure les dépendances de développement si nécessaire

    - name: Install extention
      uses: php-actions/phpunit@v3
      with:

        php_extensions: "gd"

    # Étape 5 : Exécuter les tests avec PHPUnit via l'action php-actions/phpunit
    - name: Run PHPUnit tests with php-actions/phpunit
      uses: php-actions/phpunit@v3
      with:
        version: "9.6.2"
        memory_limit: "256M"
