name: CI

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    # Étape 1 : Checkout du code source
    - name: Checkout repository
      uses: actions/checkout@v3

    # Étape 2 : Fixer le problème de sécurité Git (répertoire douteux)
    - name: Git safe directory
      run: git config --global --add safe.directory /github/workspace

    # Étape 3 : Installer les dépendances avec Composer
    - name: Install dependencies with Composer
      uses: php-actions/composer@v6
      with:
        command: install  # Utiliser "command" pour dire à Composer ce que faire
        php_version: '8.1'  # Choisir la version PHP appropriée si nécessaire
        dev: yes  # Inclure les dépendances de développement si nécessaire

    # Étape 4 : Donner les bonnes permissions à PHPUnit
    - name: Set permissions for PHPUnit
      run: chmod +x ./vendor/bin/phpunit  # Assurer que le fichier phpunit est exécutable

    # Étape 5 : Exécuter les tests avec PHPUnit
    - name: Run PHPUnit tests
      uses: php-actions/phpunit@v3
      with:
        vendored_phpunit_path: ./vendor/bin/phpunit  # Chemin vers PHPUnit
        args: tst  # Dossier contenant les tests à exécuter
