
name: CI

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies with Composer
      uses: php-actions/composer@v6 
      with:
        command: install  # Utiliser "command" pour dire à Composer ce que faire
        php_version: '8.2'  # Choisir la version PHP appropriée si nécessaire
        dev: yes  # Inclure les dépendances de développement si nécessaire
 
    - name: Run PHPUnit tests with php-actions/phpunit
      uses: php-actions/phpunit@v3
      with:
        version: 9.6.2
        php_version: "8.2"
        php_extensions: "pdo gd xdebug"
      env:
        XDEBUG_MODE: coverage

    - name: Code Coverage Report
      uses: irongut/CodeCoverageSummary@v1.3.0
      with:
        filename: coverage.cobertura.xml
        format: markdown

