name: CI

on: 
  push: 
    branches:
      - main
  pull_request: 
    branches:
      - main

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    # Étape 1 : Checkout du code source
    - name: Checkout repository
      uses: actions/checkout@v3

    # Étape 2 : Fixer les problèmes de propriété douteuse (Git)
    - name: Fix Git ownership issues
      run: git config --global --add safe.directory /app

    # Étape 3 : Installer Composer si nécessaire
    - name: Install Composer locally
      run: php -r "copy('https://getcomposer.org/composer.phar', 'composer.phar');"

    # Étape 4 : Installer les dépendances via votre binaire local
    - name: Install dependencies
      run: php composer.phar install

    # Étape 5 : Vérifier si PHPUnit est bien installé
    - name: Verify PHPUnit installation
      run: ./vendor/bin/phpunit --version

    # Étape 6 : Exécuter PHPUnit avec la configuration correcte
    - name: Run PHPUnit tests
      uses: php-actions/phpunit@v3
      with:
        phpunit_bin: ./vendor/bin/phpunit # Spécifie le chemin vers PHPUnit
        args: tst # Spécifie les tests à exécuter (dossier tst)
