name: CI

on: 
  push: 
    branches:
      - main # Exécute sur les pushes vers la branche main
  pull_request: 
    branches:
      - main # Exécute sur les PRs vers la branche main

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    # Étape 1 : Checkout du code source
    - name: Checkout repository
      uses: actions/checkout@v3

    # Étape 2 : Installer les dépendances avec une action GitHub personnalisée
    - name: Install dependencies with Composer
      uses: php-actions/composer@v6
      with:
        command: bin/composer install # Spécifie votre commande personnalisée

    # Étape 3 : Exécuter PHPUnit avec une action GitHub
    - name: Run PHPUnit tests
      uses: php-actions/phpunit@v3
      with:
        phpunit: ./vendor/bin/phpunit # Spécifie le chemin de PHPUnit
        args: tst # Dossier des tests
