name: CI

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v8.2
      
    - name: Install dependencies with Composer
      run: bin/composer install

      
    - name: Run PHPUnit tests
      uses: php-actions/phpunit@v7.4
      with:
        phpunit: ./vendor/bin/phpunit
        args: tst

