name: CI

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies with Composer
      uses: php-actions/composer@v6 
      with:
        command: install  
        php_version: '8.2' 
        dev: yes 

    - name: Run PHPUnit tests with php-actions/phpunit
      uses: php-actions/phpunit@v3
      with:
        version: 9.6.2
        php_version: "8.2"
        php_extensions: "pdo gd xdebug"
      env:
        XDEBUG_MODE: coverage

    - name: Run PHPUnit with Cobertura coverage
      run: vendor/bin/phpunit --coverage-clver coverage.cobertura.xml || true

    - name: Generate Code Coverage Summary
      uses: irongut/CodeCoverageSummary@v1.3.0
      with:
        filename: coverage.cobertura.xml
        format: markdown
        output: file

    - name: Add coverage summary to GitHub Actions Summary
      run: |
        echo "### Code Coverage Summary" >> $GITHUB_STEP_SUMMARY
        cat coverage.cobertura.xml >> $GITHUB_STEP_SUMMARY # Si tu veux inclure le fichier XML dans le summary
        echo "Markdown coverage summary will appear above!" >> $GITHUB_STEP_SUMMARY
