name: CI

on: [push]

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    steps:
    # Étape 1 : Checkout du code source
    - name: Checkout repository
      uses: actions/checkout@v3

    # Étape 2 : Configurer PHP avec la version souhaitée et installer les extensions nécessaires
    - name: Setup PHP with required extensions
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        extensions: |
          gd         
          xdebug     
        ini-values: |
          memory_limit=128M
        tools: composer # Installer Composer automatiquement

    # Étape 3 : Installer les dépendances via Composer
    - name: Install dependencies with Composer
      run: composer install --no-dev # Installer les dépendances, sans celles de dev si non nécessaires

    # Étape 4 : Exécuter les tests PHPUnit en activant les extensions PHP nécessaires
    - name: PHPUnit tests
      uses: php-actions/phpunit@v3
      with:
        php_extensions: "gd, xdebug" # Extensions activées pour PHPUnit
        coverage_clover: "coverage/clover.xml" # Générer un fichier coverage
