name: CI

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    # Étape 1 : Checkout du code source
    - name: Checkout repository
      uses: actions/checkout@v3

    # Étape 2 : Installer les dépendances avec Composer
    - name: Install dependencies with Composer
      run: bin/composer install  # Utilisation de bin/composer install pour installer les dépendances

    # Étape 3 : Exécuter les tests avec PHPUnit
    - name: Run PHPUnit tests
      uses: php-actions/phpunit@v3
      with:
        vendored_phpunit_path: ./vendor/bin/phpunit  # Le chemin vers PHPUnit dans le dossier vendor
        args: tst  # Le répertoire des tests à exécuter
