name: CI

on: 
  push: # Exécute la CI pour chaque push
    branches:
      - main # Sur la branche principale
  pull_request: # Exécute aussi la CI pour les PRs
    branches:
      - main

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    # Étape 1 : Checkout du code source
    - name: Checkout repository
      uses: actions/checkout@v3

    # Étape 2 : Installer les dépendances via Composer avec php-actions
    - name: Install dependencies
      uses: php-actions/composer@v6

    # Étape 3 : Lancer les tests PHPUnit via php-actions
    - name: Run PHPUnit tests
      uses: php-actions/phpunit@v3
      with:
        phpunit: ./vendor/bin/phpunit # Appelle votre binaire PHPUnit
        args: tst # Passe "tst" comme argument pour exécuter vos tests
