name: PHP Code Quality Check

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'

    - name: Install dependencies with Composer
      run: composer install --dev

    - name: Run PHPCS (Code Sniffer)
      uses: php-actions/phpcs@v1
      with:
        standard: PSR12
        ignore: vendor


    - name: Run PHPMD (Mess Detector)
      uses: php-actions/phpmd@v1
      with:
        rules: cleancode,unusedcode,naming
        report_format: text
        path: src

    - name: Run PHPStan
      uses: php-actions/phpstan@v3
      with:
        level: max
        paths: src
