name: PHPMD Check

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'

    - name: Composer install
      uses: php-actions/composer@v6

    - name: Run PHPMD (Mess Detector)
      uses: php-actions/phpmd@v1
      with:
        rules: cleancode,unusedcode,naming
        report_format: text
        path: lib