name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v3


      - name: Install dependencies
        uses: php-actions/composer@v6


      - name: PHP Mess Detector
        uses: php-actions/phpmd@v1
        with:
          php_version: 8.1
          path: tst/ConfigurationTest.php
          output: text
          ruleset: test/phpmd/ruleset.xml
