name: PHP Code Analysis

on: [push, pull_request]

jobs:
  phpcs:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'

    - name: Install dependencies
      run: composer install --dev

    - name: Run PHPCS
      run: vendor/bin/phpcs --standard=PSR12 --ignore=vendor .

  phpmd:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'

    - name: Install dependencies
      run: composer install --dev

    - name: Run PHPMD
      run: vendor/bin/phpmd src text cleancode,unusedcode,naming

  phpstan:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'

    - name: Install dependencies
      run: composer install --dev

    - name: Run PHPStan
      run: vendor/bin/phpstan analyse src
